In [1]:
# The following is to know when this notebook has been run and with which python version.
import time, sys
print(time.ctime())
print(sys.version.split('|')[0])

Tue Feb 11 12:21:09 2025
3.12.8 


# B Numpy

This is part of the Python lecture given by Christophe Morisset at IA-UNAM.

### Import numpy first

In [2]:
# You need first to import the numpy library (must be installed on your computer ;-) )
# As it will be widely used, better to give it a nickname, or an alias. Traditionnaly, it's "np":
import numpy as np

In [3]:
print(np.__version__)

1.26.4


### Tutorials

http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-2-Numpy.ipynb AND
http://nbviewer.ipython.org/gist/rpmuller/5920182

### The ARRAY class

#### Create an array

In [4]:
# Easy to create a numpy array (the basic class) from a list
l = [1,2,3,4,5,6]
print(l)
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
# Works with tuples also:
b = np.array((1,2,3))
print(b)

[1 2 3]


In [9]:
c = np.array(list({1,2,3}))
print(c)
print(type(c))

[1 2 3]
<class 'numpy.ndarray'>


Numpy arrays are efficiently connected to the computer:

In [11]:
L = range(1000)
%timeit L2 = [i**2 for i in L] # Notice the use of timeit, a magic function (starts with %)
A = np.arange(1000)
%timeit A2 = A**2

47.5 μs ± 255 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
703 ns ± 3.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
L = [1, 2, 3, 4]
a = np.array(L)
print(a.dtype)
print(a)

int64
[1 2 3 4]


In [17]:
L = [1, 2, 3, 4.]
a = np.array(L)
print(a.dtype)
print(a)

float64
[1. 2. 3. 4.]


In [20]:
L = [1, 2, 3, 4.5, 'a']
a = np.array(L)
print(L) # Different types can coexist in a python list
print(a.dtype)
print(a) # NOT in a numpy array. The array is re-typed to the highest type, here string.

[1, 2, 3, 4.5, 'a']
<U32
['1' '2' '3' '4.5' 'a']


Once the type of an array is defined, one can insert values of type that can be transformed to the type of the array

In [23]:
a = np.array([1, 2, 3, 4, 5, 6]) 
print(a)
a[4] = 222.78 # will be transformed to int(222.78)
print(a)
a[3] = '20' # will be tranformed to int('20')
print(a)

[1 2 3 4 5 6]
[  1   2   3   4 222   6]
[  1   2   3  20 222   6]


In [24]:
a[2] = '3.2'

ValueError: invalid literal for int() with base 10: '3.2'

In [25]:
a[2] = 'tralala'

ValueError: invalid literal for int() with base 10: 'tralala'

In [27]:
a = a.astype(float)
a[4] = 222.78 
print(a)

[  1.     2.     3.    20.   222.78   6.  ]


#### 1D, 2D, 3D, ...

In [43]:
a = np.array([1,2,3,4,5,6])
b = np.array([[1,2],[1,4], [4,7]])
c = np.array([[[47, 2, 6], [2, 4, 3]], [[66, 3, 7], [21,4, -1]]])
print(a.shape, b.shape, c.shape)
print('-' * 30)
print(b)
print('-' * 30)
print(c)
print('-' * 30)
print(b[0, 0]) 
print(c[1, 0, 2])

(6,) (3, 2) (2, 2, 3)
------------------------------
[[1 2]
 [1 4]
 [4 7]]
------------------------------
[[[47  2  6]
  [ 2  4  3]]

 [[66  3  7]
  [21  4 -1]]]
------------------------------
1
7


In [46]:
print(len(a), len(b), len(c)) # size of the first dimension
print(c.shape[0])

6 3 2
2


In [48]:
c.size

12

In [49]:
print(a.ndim, b.ndim, c.ndim)
print(len(c.shape))

1 2 3
3


In [51]:
a = np.array([1,2,3,4,5,6])
print(f'mean: {a.mean()} or {np.mean(a)}, max: {a.max()}, shape: {a.shape}, median: {np.median(a)}')

mean: 3.5 or 3.5, max: 6, shape: (6,), median: 3.5


mean and max are methods (functions) of the array class, they need ()s. shape is an atribute (like a variable).

In [52]:
print(a.mean) # this is printing information about the function, NOT the result of the function!

<built-in method mean of numpy.ndarray object at 0x1170e4030>


In [53]:
mm = a.mean # We assign to mn the function. Then we can call it directly, but still need for the ()s:
print(mm())

3.5


In [55]:
print(b)
print('----------')
print(b.shape)
print('----------')
print(b.mean()) # mean over the whole array
print('----------')
print(b.mean(axis=0)) # mean over the first axis (columns)
print('----------')
print(b.mean(1)) # mean over the raws
print('----------')
print(np.mean(b, axis=1))

[[1 2]
 [1 4]
 [4 7]]
----------
(3, 2)
----------
3.1666666666666665
----------
[2.         4.33333333]
----------
[1.5 2.5 5.5]
----------
[1.5 2.5 5.5]


In [56]:
np.mean?

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x10f7834c0>
File:            ~/anaconda3/envs/Python_Lecture/lib/python3.12/site-packages/numpy/core/fromnumeric.py
Docstring:      
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is

#### Creating arrays from scratch

In [23]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(np.linspace(0, 1, 10)) # start, stop (included), number of points
print('--------------------------------')
print(np.linspace(0, 1, 11)) # start, stop (included), number of points
print('--------------------------------')
print(np.linspace(0, 1, 10, endpoint=False)) # Not including the stop point

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
--------------------------------
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
--------------------------------
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [25]:
print(np.logspace(0, 2, 10)) # from 10**start to 10**stop, with 10 values
print('-----')
print(np.log10(np.logspace(0, 2, 10)))

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]
-----
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [26]:
print(np.zeros(2)) # Filled with 0.0
print('--------------------------------')
print(np.zeros((2,3))) # a 2D array, also filled with 0.0
print('--------------------------------')
print(np.ones_like(b)) # This is very usefull: using an already created array (or list or tuple) as example for the shape of the new one.
print('--------------------------------')
print(b)
d = np.zeros_like(b, dtype=float) + 3
print(d) # Can define a value to fille the array when creating it. Or latter...
print(np.ones_like(b, dtype=float) * 3) # Can define a value to fille the array when creating it. Or latter...

[0. 0.]
--------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
--------------------------------
[[1 1]
 [1 1]
 [1 1]]
--------------------------------
[[1 2]
 [1 4]
 [4 7]]
[[3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]]


In [27]:
new_a = a.reshape((3,2)) # This does NOT change the shape of a
print(a)
print('-------------')
print(new_a)

[1 2 3 4 5 6]
-------------
[[1 2]
 [3 4]
 [5 6]]


In [28]:
print(new_a.ravel())
print(new_a.reshape(new_a.size))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [29]:
# create 2 2D arrays (coordinates matrices), one describing how x varies, the other for y.
x, y = np.mgrid[0:5, 0:10] # This is not a function!!! notice the []
print(x.shape)
print(x)
print('------------------------------------')
print(y.shape)
print(y)

(5, 10)
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]]
------------------------------------
(5, 10)
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [30]:
# coordinates matrices using user-defined x- and y-vectors
x, y = np.meshgrid([1,2,4,7], [0.1, 0.2, 0.3])
print(x)
print('--------------------------------')
print(y)

[[1 2 4 7]
 [1 2 4 7]
 [1 2 4 7]]
--------------------------------
[[0.1 0.1 0.1 0.1]
 [0.2 0.2 0.2 0.2]
 [0.3 0.3 0.3 0.3]]


In [31]:
x, y = np.meshgrid([1,2,4,7], [0.1, 0.2, 0.3], indexing='ij') # the other order...
print(x)
print('-----------------------------------------')
print(y)

[[1 1 1]
 [2 2 2]
 [4 4 4]
 [7 7 7]]
-----------------------------------------
[[0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]]


#### WARNING arrays share memory

In [32]:
b = a.reshape((3,2))
print(a.shape, b.shape)

(6,) (3, 2)


In [33]:
b[1,1] = 100 # modify a value in the array
print(b)

[[  1   2]
 [  3 100]
 [  5   6]]


In [34]:
print(a) # !!! a and b are sharing the same place in the memory, they are pointing to the same values. 

[  1   2   3 100   5   6]


In [35]:
b[1,1], a[3] # same value

(100, 100)

In [36]:
a is b # a and b are different

False

In [37]:
print(b[1,1] == a[3])
print(b[1,1] is a[3]) # Even if the values are the same, the "is" does not tell it.

True
False


In [38]:
c = a.reshape((2,3)).copy() # This is the solution.

In [39]:
print(a)
print('---------------')
print(c)

[  1   2   3 100   5   6]
---------------
[[  1   2   3]
 [100   5   6]]


In [40]:
c[0,0] = 8888
print(a)
print('---------------')
print(c)

[  1   2   3 100   5   6]
---------------
[[8888    2    3]
 [ 100    5    6]]


### Random

In [41]:
ran_uniform = np.random.rand(5) # between 0 and 1
ran_normal = np.random.randn(5) # Gaussian mean 0 variance 1
print(ran_uniform)
print('-----------------------------')
print(ran_normal)
print('-----------------------------')
ran_normal_2D = np.random.randn(5,5) # Gaussian mean 0 variance 1
print(ran_normal_2D)

[0.54685006 0.75771896 0.84380879 0.78574851 0.58629013]
-----------------------------
[ 0.51527479 -0.81592479  0.20787448  0.20517494 -0.03139594]
-----------------------------
[[ 0.09157731  0.48056996 -0.956057   -1.93667229  1.73206657]
 [-0.5623375  -0.49354977  0.2097221  -2.87950973  0.13026634]
 [-0.55320052 -0.82726209 -1.13602221  0.32160633 -0.11506364]
 [-0.95560695 -1.13911376  1.01905769 -0.01758299  0.82277978]
 [ 0.42376156 -0.0594766   0.09927576 -0.44871027  1.78267776]]


In [42]:
np.random.seed(1)
print(np.random.rand(5))
np.random.seed(1)
print(np.random.rand(5))
np.random.seed(2)
print(np.random.rand(5))

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]
[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]
[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678 ]


### Timing on 2D array

In [43]:
N = 100
A = np.random.rand(N, N)
B = np.zeros_like(A)

In [44]:
%%timeit
for i in range(N):
    for j in range(N):
        B[i,j] = A[i,j]

1.86 ms ± 22.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [45]:
%%timeit
B = A # very faster ! It does NOT copy...

11.4 ns ± 0.16 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [46]:
%%timeit 
B = (A.copy()) # Takes more time

2.65 μs ± 8.74 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [47]:
%%timeit
for i in range(N):
    for j in range(N):
        B[i,j] = A[i,j]**2 

2.93 ms ± 64.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [48]:
%%timeit
B = A**2 # very faster ! Does a copy

2.33 μs ± 11.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [49]:
%timeit  B = (A.copy())**2 # Takes a little bit more time

5.24 μs ± 200 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Slicing

In [50]:
a = np.arange(10)
print(a)
print(a[1:8])
print(a[1:8:3])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]
[1 4 7]


In [51]:
print(a[:7])

[0 1 2 3 4 5 6]


In [52]:
print(a[4:])

[4 5 6 7 8 9]


In [53]:
print(a[::2])
print(a[::2][2])

[0 2 4 6 8]
4


In [54]:
# Revert the array:
print(a[::-1])
print(a[::-2])

[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]


#### Assignment

In [55]:
a[5:] = 999
print(a)

[  0   1   2   3   4 999 999 999 999 999]


In [56]:
a[5:] = a[4::-1] # mirror effect on the second half of the array
print(a) 

[0 1 2 3 4 4 3 2 1 0]


In [57]:
print(a)
print('-----')
b = a[:, np.newaxis] # create a new empty dimension
print(b)
print('-----')
print(a.shape, b.shape)
print('-----')
c = a[np.newaxis, :]
print(c, c.shape)

[0 1 2 3 4 4 3 2 1 0]
-----
[[0]
 [1]
 [2]
 [3]
 [4]
 [4]
 [3]
 [2]
 [1]
 [0]]
-----
(10,) (10, 1)
-----
[[0 1 2 3 4 4 3 2 1 0]] (1, 10)


In [58]:
b * c # Cross product, see below (broadcasting)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  4,  3,  2,  1,  0],
       [ 0,  2,  4,  6,  8,  8,  6,  4,  2,  0],
       [ 0,  3,  6,  9, 12, 12,  9,  6,  3,  0],
       [ 0,  4,  8, 12, 16, 16, 12,  8,  4,  0],
       [ 0,  4,  8, 12, 16, 16, 12,  8,  4,  0],
       [ 0,  3,  6,  9, 12, 12,  9,  6,  3,  0],
       [ 0,  2,  4,  6,  8,  8,  6,  4,  2,  0],
       [ 0,  1,  2,  3,  4,  4,  3,  2,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

#### Using an array

In [59]:
print(a)
print('----')
a[[2,4,6]] = -999
print(a)

[0 1 2 3 4 4 3 2 1 0]
----
[   0    1 -999    3 -999    4 -999    2    1    0]


In [60]:
# a = 1 would turn a to be 1, but if we want to assign 1 to every value in a one must do:
a[:] = 1
print(a)

[1 1 1 1 1 1 1 1 1 1]


### Using masks

In [61]:
a = np.random.randint(0, 100, 20) # min, max, N
print(a)

[74 45 50 87 88  2 52 21 55 64 48 45 23 23 37 72 20 37 14 33]


In [62]:
a < 50

array([False,  True, False, False, False,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [63]:
mask = (a < 50)

In [64]:
print(type(mask), mask.dtype)

<class 'numpy.ndarray'> bool


In [65]:
mask.sum()

12

In [66]:
N_low = (a < 50).sum()
print(N_low)

12


In [67]:
a[mask]

array([45,  2, 21, 48, 45, 23, 23, 37, 20, 37, 14, 33])

In [68]:
b = a.copy() # do NOT use b = a
b[mask] = 50 # 
print(a)
print(b)

[74 45 50 87 88  2 52 21 55 64 48 45 23 23 37 72 20 37 14 33]
[74 50 50 87 88 50 52 50 55 64 50 50 50 50 50 72 50 50 50 50]


In [69]:
b = a.copy()
b[b <= 50] = -1 # shortest way. Not matter if not even one element fit the test
print(a)
print(b)

[74 45 50 87 88  2 52 21 55 64 48 45 23 23 37 72 20 37 14 33]
[74 -1 -1 87 88 -1 52 -1 55 64 -1 -1 -1 -1 -1 72 -1 -1 -1 -1]


In [70]:
print(a[mask])
print(a[~mask]) # complementary

[45  2 21 48 45 23 23 37 20 37 14 33]
[74 50 87 88 52 55 64 72]


In [71]:
mask

array([False,  True, False, False, False,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [72]:
# New mask
mask = np.zeros_like(a, dtype=bool)
print(mask)

[False False False False False False False False False False False False
 False False False False False False False False]


In [73]:
mask[[2,3,4]] = True

In [74]:
mask

array([False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [75]:
a[mask]

array([50, 87, 88])

In [76]:
a[mask].sum()

225

In [77]:
a[mask].mean()

75.0

#### Working on 2D

In [78]:
b = a.copy().reshape(4,5)
b

array([[74, 45, 50, 87, 88],
       [ 2, 52, 21, 55, 64],
       [48, 45, 23, 23, 37],
       [72, 20, 37, 14, 33]])

In [79]:
mask = b < 50

In [80]:
mask

array([[False,  True, False, False, False],
       [ True, False,  True, False, False],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [81]:
# The result has now only 1D
b[mask]

array([45,  2, 21, 48, 45, 23, 23, 37, 20, 37, 14, 33])

In [82]:
b[mask] = -1

In [83]:
b

array([[74, -1, 50, 87, 88],
       [-1, 52, -1, 55, 64],
       [-1, -1, -1, -1, -1],
       [72, -1, -1, -1, -1]])

#### combining masks

In [84]:
print(a)
mask_low = a > 30
mask_high = a < 70
print('-------------------------------------')
print(a[mask_low & mask_high]) # both conditions are filled
print('-------------------------------------')
print(a[~mask_low | ~mask_high]) # complementary, using the | for OR

[74 45 50 87 88  2 52 21 55 64 48 45 23 23 37 72 20 37 14 33]
-------------------------------------
[45 50 52 55 64 48 45 37 37 33]
-------------------------------------
[74 87 88  2 21 23 23 72 20 14]


#### the where function

In [85]:
tt = np.where(a > 30)
print(a)
print(tt) # tt is a tuple of arrays, one for each dimension of the condition, 
# containing the indices where the condition is filled in that dimension.

[74 45 50 87 88  2 52 21 55 64 48 45 23 23 37 72 20 37 14 33]
(array([ 0,  1,  2,  3,  4,  6,  8,  9, 10, 11, 14, 15, 17, 19]),)


In [86]:
(a > 30).nonzero() # "where" is the same than condition.nonzero(). 

(array([ 0,  1,  2,  3,  4,  6,  8,  9, 10, 11, 14, 15, 17, 19]),)

In [87]:
# the indices where the condition is filled are in the first element of the tuple

In [88]:
tt[0]

array([ 0,  1,  2,  3,  4,  6,  8,  9, 10, 11, 14, 15, 17, 19])

In [89]:
# faster once you know that the condition is 1D
tt = np.where(a > 30)[0]

In [90]:
tt # the array containing the indices where the condition is filled

array([ 0,  1,  2,  3,  4,  6,  8,  9, 10, 11, 14, 15, 17, 19])

In [91]:
a[tt] # the values where the condition is filled

array([74, 45, 50, 87, 88, 52, 55, 64, 48, 45, 37, 72, 37, 33])

In [92]:
# The where function can take 3 arguments. 
b = np.where(a < 50, np.nan, a)
print(a)
print(b)
print(np.isfinite(b))

[74 45 50 87 88  2 52 21 55 64 48 45 23 23 37 72 20 37 14 33]
[74. nan 50. 87. 88. nan 52. nan 55. 64. nan nan nan nan nan 72. nan nan
 nan nan]
[ True False  True  True  True False  True False  True  True False False
 False False False  True False False False False]


In [93]:
b = np.where(a < 50, True, False)
print(a)
print(b)

[74 45 50 87 88  2 52 21 55 64 48 45 23 23 37 72 20 37 14 33]
[False  True False False False  True False  True False False  True  True
  True  True  True False  True  True  True  True]


In [94]:
b = np.where(a < 50, 0, 100)
print(a)
print(b)

[74 45 50 87 88  2 52 21 55 64 48 45 23 23 37 72 20 37 14 33]
[100   0 100 100 100   0 100   0 100 100   0   0   0   0   0 100   0   0
   0   0]


### Some operations with arrays

In [95]:
a 

array([74, 45, 50, 87, 88,  2, 52, 21, 55, 64, 48, 45, 23, 23, 37, 72, 20,
       37, 14, 33])

In [96]:
a + 1

array([75, 46, 51, 88, 89,  3, 53, 22, 56, 65, 49, 46, 24, 24, 38, 73, 21,
       38, 15, 34])

In [97]:
a**2 + 3*a**3

array([1221148,  275400,  377500, 1983078, 2052160,      28,  424528,
         28224,  502150,  790528,  334080,  275400,   37030,   37030,
        153328, 1124928,   24400,  153328,    8428,  108900])

In [98]:
# look for the integers I so that i**2 + (i+1)**2 = (i+2)**2
i = np.arange(30)
b = i**2 + (i+1)**2

In [99]:
c = (i+2)**2

In [100]:
print(b)
print(c)

[   1    5   13   25   41   61   85  113  145  181  221  265  313  365
  421  481  545  613  685  761  841  925 1013 1105 1201 1301 1405 1513
 1625 1741]
[  4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324 361
 400 441 484 529 576 625 676 729 784 841 900 961]


In [101]:
b == c

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [102]:
i[b==c]

array([3])

In [103]:
i[b==c][0] # the result is an array. To obtain the first value (here the only one), use [0]

3

Numpy manages almost any mathematical operation. log, trigo, etc

In [104]:
a = np.arange(18)
print(a)
print('-'*50)
print(np.log10(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
--------------------------------------------------
[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251 1.         1.04139269
 1.07918125 1.11394335 1.14612804 1.17609126 1.20411998 1.23044892]


/var/folders/7b/7gktm_g91hn54p3gxj15kb1m0000gn/T/ipykernel_34318/574489494.py:4: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(a))


In [105]:
for aa in a:
    print('{0:2} {1:4.2f} {2:5.2f} {3:8.2e}'.format(aa, np.log10(aa), np.sin(aa), np.exp(aa)))

 0 -inf  0.00 1.00e+00
 1 0.00  0.84 2.72e+00
 2 0.30  0.91 7.39e+00
 3 0.48  0.14 2.01e+01
 4 0.60 -0.76 5.46e+01
 5 0.70 -0.96 1.48e+02
 6 0.78 -0.28 4.03e+02
 7 0.85  0.66 1.10e+03
 8 0.90  0.99 2.98e+03
 9 0.95  0.41 8.10e+03
10 1.00 -0.54 2.20e+04
11 1.04 -1.00 5.99e+04
12 1.08 -0.54 1.63e+05
13 1.11  0.42 4.42e+05
14 1.15  0.99 1.20e+06
15 1.18  0.65 3.27e+06
16 1.20 -0.29 8.89e+06
17 1.23 -0.96 2.42e+07


/var/folders/7b/7gktm_g91hn54p3gxj15kb1m0000gn/T/ipykernel_34318/1054177423.py:2: RuntimeWarning: divide by zero encountered in log10
  print('{0:2} {1:4.2f} {2:5.2f} {3:8.2e}'.format(aa, np.log10(aa), np.sin(aa), np.exp(aa)))


sum

In [106]:
print(a.sum())
print(17*18/2)

153
153.0


### Multi-D

In [107]:
a = np.random.rand(2, 4, 3)
print(a)
print(a.shape)
print(a.size)

[[[0.81335859 0.93082305 0.60493369]
  [0.38254158 0.71181092 0.70453504]
  [0.67070747 0.14534246 0.99501085]
  [0.29646046 0.41209886 0.45155358]]

 [[0.24733118 0.44588879 0.59504362]
  [0.20667767 0.14452134 0.78107716]
  [0.74448703 0.17289356 0.72843443]
  [0.81223262 0.01271812 0.52927933]]]
(2, 4, 3)
24


2 planes, 4 rows, 3 columns

A small comment on the order of the elements in arrays in Python: There is two ways arrays can be stored: row- or column major. It has a direct impact on the way one has to loop on the arrays. IDL is like Fortran (column major) and Python is like C (row major). It means that in Python, as you move linearly through the memory of an array, the second dimension (rightmost) changes the fastest, while in IDL the first (leftmost) dimension changes the fastest. Consequence on the loop order in Python:

In [108]:
for plane in a:
    for row in plane:
        for col in row:
            print(col)
            print('-----')

0.8133585911465945
-----
0.9308230470336025
-----
0.6049336920996311
-----
0.3825415811237336
-----
0.7118109154009248
-----
0.7045350429924633
-----
0.670707474072497
-----
0.14534246264089723
-----
0.9950108542563543
-----
0.2964604554800414
-----
0.4120988629759421
-----
0.45155357536110907
-----
0.24733117516820646
-----
0.4458887895849456
-----
0.5950436232350703
-----
0.20667766554654865
-----
0.1445213435994629
-----
0.7810771602659407
-----
0.7444870253883633
-----
0.17289356036748627
-----
0.7284344326235983
-----
0.8122326225736135
-----
0.01271812496340985
-----
0.5292793289385392
-----


It is like in a book: letter by letter, row by row, page after page.

In [109]:
print(a[0,1,2]) # a[p, r, c]

0.7045350429924633


In [110]:
a.sum()

12.539761406838977

In [111]:
a.sum(0) # from 3D to 2D. Generate an "image" of the sum, i.e. the "projection" on the x-axis of the 3D array

array([[1.06068977, 1.37671184, 1.19997732],
       [0.58921925, 0.85633226, 1.4856122 ],
       [1.4151945 , 0.31823602, 1.72344529],
       [1.10869308, 0.42481699, 0.9808329 ]])

In [112]:
a.sum(0).shape

(4, 3)

In [113]:
a.sum(0).sum(0) # from 3D to 1D. From the image, make the sum in each row.

array([4.17379659, 2.97609711, 5.38986771])

In [114]:
a.ravel()

array([0.81335859, 0.93082305, 0.60493369, 0.38254158, 0.71181092,
       0.70453504, 0.67070747, 0.14534246, 0.99501085, 0.29646046,
       0.41209886, 0.45155358, 0.24733118, 0.44588879, 0.59504362,
       0.20667767, 0.14452134, 0.78107716, 0.74448703, 0.17289356,
       0.72843443, 0.81223262, 0.01271812, 0.52927933])

In [115]:
a.min()

0.01271812496340985

In [116]:
i_min = a.argmin() # return the index of where the minimum is. It uses the 1D index.
print(i_min)
b = np.array([10,2,3,4,5,2])
b.argmin() # only the first occurence

22


1

In [117]:
a.ravel().shape # 1D 

(24,)

In [118]:
a.ravel()[i_min] # Check where the minimum is.

0.01271812496340985

In [119]:
z = i_min // 12
y = (i_min - 12*z) // 3
x = i_min - 12*z - 3*y
print(z, y, x)
print(a[z, y, x])

1 3 1
0.01271812496340985


In [120]:
def decompose_ravel(arr, i):
    """
    inputs: 
        arr: mulit-dimentional array
        i: index in the 1D realisation of arr
    output:
        tuple pf the coordinates corresponding to i
    """
    shapes = arr.shape
    idx = i
    res = []
    for i in np.arange(arr.ndim):
        subdims = np.prod(shapes[i+1:])
        n = int(idx // subdims)
        #print n, subdims, idx
        idx = idx - subdims*n
        res.append(n)
    return tuple(res)

In [121]:
res = decompose_ravel(a, i_min)
print(a.min())
print(res)
print(a[res])

0.01271812496340985
(1, 3, 1)
0.01271812496340985


In [122]:
decompose_ravel(a, 2)

(0, 0, 2)

In [123]:
a.min(0).min(0)

array([0.20667767, 0.01271812, 0.45155358])

In [124]:
print(a[:,0,0])
a[:,0,0].min()

[0.81335859 0.24733118]


0.24733117516820646

In [125]:
a

array([[[0.81335859, 0.93082305, 0.60493369],
        [0.38254158, 0.71181092, 0.70453504],
        [0.67070747, 0.14534246, 0.99501085],
        [0.29646046, 0.41209886, 0.45155358]],

       [[0.24733118, 0.44588879, 0.59504362],
        [0.20667767, 0.14452134, 0.78107716],
        [0.74448703, 0.17289356, 0.72843443],
        [0.81223262, 0.01271812, 0.52927933]]])

In [126]:
a.mean(axis=1)

array([[0.54076703, 0.55001882, 0.68900829],
       [0.50268212, 0.19400545, 0.65845864]])

In [127]:
np.median(a, 1)

array([[0.52662453, 0.56195489, 0.65473437],
       [0.4959091 , 0.15870745, 0.66173903]])

In [128]:
a.std(2)

array([[0.13476016, 0.15353285, 0.35009799, 0.06581353],
       [0.1424298 , 0.28655065, 0.26574893, 0.33101216]])

In [129]:
np.percentile(a, 25)

0.2841781354020827

In [130]:
print(a[0:4,0])
print(np.cumsum(a[:,0])) # axis is a keyword. If absent, applied on the ravel(), e.g. 1D array

[[0.81335859 0.93082305 0.60493369]
 [0.24733118 0.44588879 0.59504362]]
[0.81335859 1.74418164 2.34911533 2.59644651 3.0423353  3.63737892]


In [131]:
b = np.arange(1000).reshape(10,10,10)

In [132]:
b.shape

(10, 10, 10)

In [133]:
b[4,:,:] # hundreds digits = 4

array([[400, 401, 402, 403, 404, 405, 406, 407, 408, 409],
       [410, 411, 412, 413, 414, 415, 416, 417, 418, 419],
       [420, 421, 422, 423, 424, 425, 426, 427, 428, 429],
       [430, 431, 432, 433, 434, 435, 436, 437, 438, 439],
       [440, 441, 442, 443, 444, 445, 446, 447, 448, 449],
       [450, 451, 452, 453, 454, 455, 456, 457, 458, 459],
       [460, 461, 462, 463, 464, 465, 466, 467, 468, 469],
       [470, 471, 472, 473, 474, 475, 476, 477, 478, 479],
       [480, 481, 482, 483, 484, 485, 486, 487, 488, 489],
       [490, 491, 492, 493, 494, 495, 496, 497, 498, 499]])

In [134]:
b[:,2,:] # tens digit = 2

array([[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [220, 221, 222, 223, 224, 225, 226, 227, 228, 229],
       [320, 321, 322, 323, 324, 325, 326, 327, 328, 329],
       [420, 421, 422, 423, 424, 425, 426, 427, 428, 429],
       [520, 521, 522, 523, 524, 525, 526, 527, 528, 529],
       [620, 621, 622, 623, 624, 625, 626, 627, 628, 629],
       [720, 721, 722, 723, 724, 725, 726, 727, 728, 729],
       [820, 821, 822, 823, 824, 825, 826, 827, 828, 829],
       [920, 921, 922, 923, 924, 925, 926, 927, 928, 929]])

In [135]:
b[:,:,7] # unity digit = 7

array([[  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [107, 117, 127, 137, 147, 157, 167, 177, 187, 197],
       [207, 217, 227, 237, 247, 257, 267, 277, 287, 297],
       [307, 317, 327, 337, 347, 357, 367, 377, 387, 397],
       [407, 417, 427, 437, 447, 457, 467, 477, 487, 497],
       [507, 517, 527, 537, 547, 557, 567, 577, 587, 597],
       [607, 617, 627, 637, 647, 657, 667, 677, 687, 697],
       [707, 717, 727, 737, 747, 757, 767, 777, 787, 797],
       [807, 817, 827, 837, 847, 857, 867, 877, 887, 897],
       [907, 917, 927, 937, 947, 957, 967, 977, 987, 997]])

In [136]:
b.min(0) # elements with the smallest value for the hundreds digit

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [137]:
b.min(2) # smallest value for the unity digit

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540, 550, 560, 570, 580, 590],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [700, 710, 720, 730, 740, 750, 760, 770, 780, 790],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [900, 910, 920, 930, 940, 950, 960, 970, 980, 990]])

In [138]:
b.min(2).shape

(10, 10)

In [139]:
np.median(b)

499.5

In [140]:
np.median(b, axis=0)

array([[450., 451., 452., 453., 454., 455., 456., 457., 458., 459.],
       [460., 461., 462., 463., 464., 465., 466., 467., 468., 469.],
       [470., 471., 472., 473., 474., 475., 476., 477., 478., 479.],
       [480., 481., 482., 483., 484., 485., 486., 487., 488., 489.],
       [490., 491., 492., 493., 494., 495., 496., 497., 498., 499.],
       [500., 501., 502., 503., 504., 505., 506., 507., 508., 509.],
       [510., 511., 512., 513., 514., 515., 516., 517., 518., 519.],
       [520., 521., 522., 523., 524., 525., 526., 527., 528., 529.],
       [530., 531., 532., 533., 534., 535., 536., 537., 538., 539.],
       [540., 541., 542., 543., 544., 545., 546., 547., 548., 549.]])

In [141]:
x = 2 * np.random.rand(100,100,100) - 1.
print(np.min(x), np.max(x))

-0.9999981048433622 0.999995332233139


In [142]:
y = 2 * np.random.rand(100,100,100) - 1.
z = 2 * np.random.rand(100,100,100) - 1.

In [143]:
r = np.sqrt(x**2 + y**2 + z**2)
print(np.min(r), np.max(r))
print(np.sqrt(3))

0.005805115410170653 1.7193083530710265
1.7320508075688772


In [144]:
print(np.mean(r))
print(r.mean())

0.9613303545519957
0.9613303545519957


In [145]:
np.median(r)

0.9855939090490047

### Broadcasting

http://arxiv.org/pdf/1102.1523.pdf

    If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.
    If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [146]:
x1 = np.array((1,2,3,4,5))
y1 = np.array((1,2,3,4,5))
z1 = np.array((1,2,3,4,5))
r1 = x1 * y1 * z1
print(r1.shape)
print(r1)

(5,)
[  1   8  27  64 125]


In [147]:
x = np.array((1,2,3,4,5)).reshape(5,1,1)

In [148]:
x

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [149]:
x.shape

(5, 1, 1)

In [150]:
x.ndim

3

In [151]:
y = np.array((1,2,3,4,5)).reshape(1,5,1)
z = np.array((1,2,3,4,5)).reshape(1,1,5)
print(y)
print(z)

[[[1]
  [2]
  [3]
  [4]
  [5]]]
[[[1 2 3 4 5]]]


In [152]:
r = x * y * z

In [153]:
print(r.shape)

(5, 5, 5)


In [154]:
r

array([[[  1,   2,   3,   4,   5],
        [  2,   4,   6,   8,  10],
        [  3,   6,   9,  12,  15],
        [  4,   8,  12,  16,  20],
        [  5,  10,  15,  20,  25]],

       [[  2,   4,   6,   8,  10],
        [  4,   8,  12,  16,  20],
        [  6,  12,  18,  24,  30],
        [  8,  16,  24,  32,  40],
        [ 10,  20,  30,  40,  50]],

       [[  3,   6,   9,  12,  15],
        [  6,  12,  18,  24,  30],
        [  9,  18,  27,  36,  45],
        [ 12,  24,  36,  48,  60],
        [ 15,  30,  45,  60,  75]],

       [[  4,   8,  12,  16,  20],
        [  8,  16,  24,  32,  40],
        [ 12,  24,  36,  48,  60],
        [ 16,  32,  48,  64,  80],
        [ 20,  40,  60,  80, 100]],

       [[  5,  10,  15,  20,  25],
        [ 10,  20,  30,  40,  50],
        [ 15,  30,  45,  60,  75],
        [ 20,  40,  60,  80, 100],
        [ 25,  50,  75, 100, 125]]])

In [155]:
a = np.ones((10,11))
b = np.arange(10).reshape(10,1)
print(a)
print(b)
print(b.shape)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [156]:
a * b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [157]:
a * 2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [158]:
a * b.reshape(1,10)

ValueError: operands could not be broadcast together with shapes (10,11) (1,10) 

### Structured arrays and RecArrays

See here: http://docs.scipy.org/doc/numpy/user/basics.rec.html

A structured array in numpy is an array of records. Each record can contain one or more items which can be of different types.

In [159]:
a = np.array([(1.5, 2), (3.0, 4)]) # Classical numpy array
print(a)

[[1.5 2. ]
 [3.  4. ]]


In [160]:
astru = np.array([(1.5, 2), (3.0, 4)], dtype=[('x', float), ('y', int)]) # array with named and typed columns
astru

array([(1.5, 2), (3. , 4)], dtype=[('x', '<f8'), ('y', '<i8')])

In [161]:
print(astru)

[(1.5, 2) (3. , 4)]


In [162]:
print(astru['x'])
print(astru['y'])

[1.5 3. ]
[2 4]


In [163]:
arec = astru.view(np.recarray)
print(type(a), type(astru), type(arec))
print('----------------------------------')
print(a)
print(astru)
print(arec)
print('----------------------------------')
print('SIZEs:', a.size, astru.size, arec.size) # not even the same sixe
print('----------------------------------')
print('NDIMs:', a.ndim, astru.ndim, arec.ndim) # not even the same sixe
print('----------------------------------')
print('DTYPEs:', a.dtype, astru.dtype, arec.dtype) # types tell us that ar has column names and types
print('----------------------------------')
print(a[1,1], astru[1][1], arec[1][1]) # one is 2D, the other is a collection of 1D
print('----------------------------------')
print(astru['y'], arec['y']) # acces by name (a litle like dictionnaries)
print('----------------------------------')
print(arec.x)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.recarray'>
----------------------------------
[[1.5 2. ]
 [3.  4. ]]
[(1.5, 2) (3. , 4)]
[(1.5, 2) (3. , 4)]
----------------------------------
SIZEs: 4 2 2
----------------------------------
NDIMs: 2 1 1
----------------------------------
DTYPEs: float64 [('x', '<f8'), ('y', '<i8')] (numpy.record, [('x', '<f8'), ('y', '<i8')])
----------------------------------
4.0 4 4
----------------------------------
[2 4] [2 4]
----------------------------------
[1.5 3. ]


In [164]:
%timeit astru2 = np.append(astru, np.array([(5.0, 6)], dtype=astru.dtype)) # Copied all the data, may be slow

4.92 μs ± 40.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [165]:
%timeit astru3 = np.concatenate((astru, np.array([(5.0, 6)], dtype=astru.dtype))) # A little bit faster

4.35 μs ± 98.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [166]:
%timeit arec2 = np.append(arec, np.array([(5.0, 6)], dtype=astru.dtype).view(np.recarray)) # Copied all the data, may be slow

9.25 μs ± 284 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [167]:
%timeit arec3 = np.concatenate((arec, np.array([(5.0, 6)], dtype=astru.dtype).view(np.recarray))) # A little bit faster

7.39 μs ± 137 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [168]:
arec4 = np.rec.fromrecords([(456,'dbe',1.2),(2,'de',1.3)],names='col1,col2,col3') # direct from data.
print(arec4)
print(type(arec4))
print(arec4.col1[1])
print(arec4[1].col1)

[(456, 'dbe', 1.2) (  2, 'de', 1.3)]
<class 'numpy.recarray'>
2
2


In [169]:
arec4 = np.rec.fromrecords([('etoile_15', 30.015, -0.752, 10.722), 
                            ('etoile_11', 31.163, -9.109, 10.761),
                            ('etoile_16', 39.789, -7.716, 11.071), 
                            ('etoile_14', 35.110, 6.785, 11.176), 
                            ('etoile_31', 33.530, 9.306, 11.823), 
                            ('etoile_04', 33.480, 5.568, 11.978)
                            ],
                           names='name,ra,dec, mag')

In [170]:
mask = arec4.mag > 11.
print(arec4[mask])
print('-------------------------')
for star in arec4[mask]:
    print('name: {0} ra = {1} dec = {2} magnitude = {3}'.format(star.name, star.ra, star.dec, star.mag))
print('-------------------------')
for star in arec4[mask]:
    print('name: {0[name]} ra = {0[ra]} dec = {0[dec]} magnitude = {0[mag]}'.format(star)) # use only one key in format

[('etoile_16', 39.789, -7.716, 11.071)
 ('etoile_14', 35.11 ,  6.785, 11.176)
 ('etoile_31', 33.53 ,  9.306, 11.823)
 ('etoile_04', 33.48 ,  5.568, 11.978)]
-------------------------
name: etoile_16 ra = 39.789 dec = -7.716 magnitude = 11.071
name: etoile_14 ra = 35.11 dec = 6.785 magnitude = 11.176
name: etoile_31 ra = 33.53 dec = 9.306 magnitude = 11.823
name: etoile_04 ra = 33.48 dec = 5.568 magnitude = 11.978
-------------------------
name: etoile_16 ra = 39.789 dec = -7.716 magnitude = 11.071
name: etoile_14 ra = 35.11 dec = 6.785 magnitude = 11.176
name: etoile_31 ra = 33.53 dec = 9.306 magnitude = 11.823
name: etoile_04 ra = 33.48 dec = 5.568 magnitude = 11.978


### NaN and other ANSI values

In [171]:
a = np.array([-3, -2., -1., 0., 1., 2.])
b = 1./a
print(b)

[-0.33333333 -0.5        -1.                 inf  1.          0.5       ]


/var/folders/7b/7gktm_g91hn54p3gxj15kb1m0000gn/T/ipykernel_34318/3565680072.py:2: RuntimeWarning: divide by zero encountered in divide
  b = 1./a


In [172]:
print(a.sum())
print(b.sum()) # NaN and others are absorbant elements

-3.0
inf


In [173]:
mask = np.isfinite(b)
print(mask)
print(b[mask].sum())

[ True  True  True False  True  True]
-0.33333333333333326


In [174]:
for elem in b:
    print(np.isinf(elem))

False
False
False
True
False
False


In [175]:
a = np.array([-2, -1, 1., 2, 3])
b = np.log10(a)
mask = np.isfinite(b)
print(a)
print(b)
print(mask)
print(a.mean())
print(b.mean())
print(b[mask].mean())
print(np.nanmean(b))

[-2. -1.  1.  2.  3.]
[       nan        nan 0.         0.30103    0.47712125]
[False False  True  True  True]
0.6
nan
0.25938375012788123
0.25938375012788123


/var/folders/7b/7gktm_g91hn54p3gxj15kb1m0000gn/T/ipykernel_34318/1339020013.py:2: RuntimeWarning: invalid value encountered in log10
  b = np.log10(a)


### Roundish values of floats

In [176]:
import math
res = []
for i in range(100): 
    res.append(math.log(2 ** i, 2)) # The second argument is the base of the log. The result should be i.
print(res)
# We can see that sometimes the value of log2(2**i) is NOT i.

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.000000000000004, 30.0, 31.000000000000004, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.00000000000001, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.00000000000001, 48.0, 49.0, 50.0, 51.00000000000001, 52.0, 53.0, 54.0, 55.00000000000001, 56.0, 57.0, 58.00000000000001, 59.00000000000001, 60.0, 61.0, 62.00000000000001, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.00000000000001, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.00000000000001, 94.00000000000001, 95.00000000000001, 96.0, 97.0, 98.0, 99.0]


In [177]:
res2 = []
for i in range(100): 
    res2.append(float(round(math.log(2**i, 2))) == math.log(2 ** i, 2))
print(res2)
# An equivalent result is obtained when comparing the round value. This should be always True.

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, False, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, False, True, True, True, False, True, True, True, False, True, True, False, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, True, True, True, True]


In [178]:
res = []
for i in range(100): 
    res.append(np.log2(2.**i)) # Using np.log2(). The result should be i.
print(res)

res_np = []
for i in range(100): 
    res_np.append(float(round(np.log2(2.**i))) == np.log2(2.**i))
print(res_np)
# No problemes with the numpy log function.

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

In case of doubdts, one can use the close function from numpy:

In [179]:
res_np2 = []
for i in range(100): 
    res_np2.append(np.isclose(float(round(math.log(2 ** i, 2))), math.log(2 ** i, 2)))
print(res_np2)
# The isclose 

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]


In [180]:
np.isclose?

Signature:       np.isclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
Call signature:  np.isclose(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function isclose at 0x113026700>
File:            ~/anaconda3/envs/Python_Lecture/lib/python3.12/site-packages/numpy/core/numeric.py
Docstring:      
Returns a boolean array where two arrays are element-wise equal within a
tolerance.

The tolerance values are positive, typically very small numbers.  The
relative difference (`rtol` * abs(`b`)) and the absolute difference
`atol` are added together to compare against the absolute difference
between `a` and `b`.

.. warning:: The default `atol` is not appropriate for comparing numbers
             that are much smaller than one (see Notes).

Parameters
----------
a, b : array_like
    Input arrays to compare.
rtol : float
    The relative tolerance parameter (see Notes).
atol : float
    The absolute tolerance parameter (see Notes).
equal_nan : bool
    Whether t

In [181]:
res_np2 = []
for i in range(100):
    res1 = math.log(2 ** i, 2)
    res2 = float(round(res1))
    res1_eq_res2 = np.abs(res2 - res1) < 0.000001
    res_np2.append(res1_eq_res2)
print(res_np2)
# The isclose 

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
